### ISSUE TITLE
Xiaomi Motion Sensor RTCGQ01LM Not Showing

### ISSUE THREAD

**Issue by killer23d** [veonua/SmartThingsEdge-Xiaomi#14]
Added the Edge driver, and removed the device and DTH. Live Log shows the following:

`[cb4e4911-ee5c-4703-8b48-aa11513c8b56](https://graph-na04-useast2.api.smartthings.com/ide/logs#cb4e4911-ee5c-4703-8b48-aa11513c8b56) 11:07:12 PM: debug SmartShield(text: null, manufacturerId: 0x0b39, direction: 0x00, data: [0xcb, 0xcb, 0xcb], number: null, isManufacturerSpecific: true, messageType: 0x00, senderShortId: 0x100e, isClusterSpecific: false, sourceEndpoint: 0x01, profileId: 0x0104, command: 0xcb, clusterId: 0x0006, destinationEndpoint: 0x01, options: 0x0000)
[cb4e4911-ee5c-4703-8b48-aa11513c8b56](https://graph-na04-useast2.api.smartthings.com/ide/logs#cb4e4911-ee5c-4703-8b48-aa11513c8b56) 11:07:12 PM: warn DID NOT PARSE MESSAGE for description : catchall: 0104 0006 01 01 0000 00 100E 00 01 0B39 CB 00 CBCBCB
[cb4e4911-ee5c-4703-8b48-aa11513c8b56](https://graph-na04-useast2.api.smartthings.com/ide/logs#cb4e4911-ee5c-4703-8b48-aa11513c8b56) 11:07:12 PM: debug description is catchall: 0104 0006 01 01 0000 00 100E 00 01 0B39 CB 00 CBCBCB`

Sensor is still not showing up.

**Comment by veonua** [comment]
https://graph-na04-useast2.api.smartthings.com/ide/ is obsolete now

use new Edge environment and toolset.

**Comment by killer23d** [comment]
Sorry, let me clarify. I added the driver from your invitation. I then used the app to Scan Nearby but nothing shows up. Upon checking the live logs (which I posted above), those CATCHALL entries show up. I think the motion sensor is not forwarding the fingerprints. I reset the Xiaomi devices properly as I was adding other devices with the Edge drivers from another developers without issues.

**Comment by veonua** [comment]
if you are looking to IDE , you are doing something wrong. Please refer to the Edge docs. 

I would recommend remove everything from IDE and switch to CLI and mobile application

**Comment by veonua** [comment]
https://community.smartthings.com/t/st-edge-beta-xiaomi-aqara-tuya-zigbee-sensors-driver/234709/375  

this post might help you

**Comment by killer23d** [comment]
Report back, the issues I am having is fixed after I uninstalled and reinstalled the driver. The motion sensor is now detected.

**Comment by krystian50** [comment]
@veonua I think the same issue here. I reinstalled the driver, but still not showing up. Screenshot:
<img width="430" alt="image" src="https://github.com/veonua/SmartThingsEdge-Xiaomi/assets/19366440/d77f02e4-40a8-4941-834d-b73804a9bfb2">
